service: fut-booking-back
app: fut-booking

frameworkVersion: "3"

plugins:
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
  
  environment:
    futBookingTableName: ${self:custom.futBookingTableName}

package:
  individually: true
  patterns:
    - "!**/*"

custom:
  futBookingTableName: ${self:provider.stage}-fut-booking

functions:
  getGames:
    handler: src/functions/getGames/index.handler
    package:
      patterns:
        - src/common/**
        - package.json
        - src/functions/getGames/**
  getField:
    handler: src/functions/getField/index.handler
    package:
      patterns:
        - src/common/**
        - package.json
        - src/functions/getField/**
    iamRoleStatements:
        - Effect: "Allow"
          Action:
            - dynamodb:GetItem
          Resource:
            - !GetAtt FutBookingTable.Arn
  getFields:
    handler: src/functions/getFields/index.handler
    package:
      patterns:
        - src/common/**
        - package.json
        - src/functions/getFields/**
    iamRoleStatements:
        - Effect: "Allow"
          Action:
            - dynamodb:Query
          Resource:
            - !GetAtt FutBookingTable.Arn
  createField:
    handler: src/functions/createField/index.handler
    package:
      patterns:
        - src/common/**
        - package.json
        - src/functions/createField/**
    iamRoleStatements:
        - Effect: "Allow"
          Action:
            - dynamodb:PutItem
          Resource:
            - !GetAtt FutBookingTable.Arn

resources:
  Resources:
    FutBookingTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.futBookingTableName}
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
          - AttributeName: gameWeek
            AttributeType: S
          - AttributeName: gameDateTime
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: gameWeek-gameDateTime-index
            KeySchema:
              - AttributeName: gameWeek
                KeyType: HASH
              - AttributeName: gameDateTime
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
          - IndexName: SK-gameDateTime-index
            KeySchema:
              - AttributeName: SK
                KeyType: HASH
              - AttributeName: gameDateTime
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_IMAGE