name: Deploy master branch

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Run unit tests
      run: npm run test
    - name: Serverless deploy
      uses: serverless/github-action@v3.2
      with:
        args: deploy --param="email=${{secrets.COGNITO_EMAIL}}"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Run integration tests
      run: |
        ls
        cat slsoutput.toml
        cat slsoutput.toml | tr -d "[:blank:]" > .slsoutput
        rm slsoutput.toml
        cat .slsoutput
        npm run export-env-local
        ./config/getAuthToken.sh
        npm run integration
        ./config/deleteCognitoUser.sh
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}